/* original Spectrum font by Factor6 */
/* remixed for iPod by Gasman */

/* . = background */
/*   = black */
/* X = dkgrey */
/* o = ltgrey */
/* O = white */

static unsigned char *al_font_spc[] = {
"................",
"................",
"................",
"................",
"................",
"................",
"................",
"................",
"................",
"................",
"................",
"................",
"................",
"................",
"................",
"................"
};
static unsigned char *al_font_exc[] = {
"XXXXX .",
"XOOOO .",
"XOoOo .",
"XOOoo .",
"XoOoo .",
"XOooX .",
"Xoooo .",
"XooXo .",
"XoXoX .",
"XooXX .",
"XoXXX .",
"      .",
".......",
"XXXXX .",
"XOooo .",
"      ."
};
static unsigned char *al_font_apos[] = {
"XXXXXX..",
".OOOOo .",
".      .",
"........",
"........",
"........",
"........",
"........",
"........",
"........",
"........",
"........",
"........",
"........",
"........",
"........"
};
static unsigned char *al_font_a[] = {
"................",
"................",
"................",
"....XXXXXXX.....",
"....XOOOOOO  ...",
"....     OOOo ..",
"......... OoO ..",
"....XXXXX Oooo .",
"..XXOOOOOOOoXo .",
".XOOO     oooo .",
".XOOo ...XooXX .",
"XOOoO ...XoXoX .",
"XOoOo ...XXoXX .",
"XoOoo XXXXoXXX .",
"XOooooXoXoXXXX .",
"               ."
};
static unsigned char *al_font_b[] = {
"XXXXX ..........",
"XOOOO ..........",
"XOOOO ..........",
"XOOOO XXXXX.....",
"XOOOOOOOOOO  ...",
"XOOOO     oOo ..",
"XOOOO ...Xooo ..",
"XOOOo ...XoooX .",
"XOOoO ...Xoooo .",
"XOoOo ...XoXoX .",
"XOooo ...XooXX .",
"XoOoo ...XoXoX .",
"XOooo ...XXoXX .",
"Xoooo XXXXoXXX .",
"XoooooXoXoXXXX .",
"               ."
};
static unsigned char *al_font_c[] = {
"................",
"................",
"................",
"XXXXXXXXX ......",
"XOOOOOOOO ......",
"XOOOO     ......",
"XOOOo ..........",
"XOOOo ..........",
"XOOoO ..........",
"XOoOo ..........",
"XOooo ..........",
"XoOoo ..........",
". ooo ..........",
". ooo XXXXXXXX .",
"..  ooXooXoXXX .",
"....           ."
};
static unsigned char *al_font_d[] = {
".........XXXXX .",
".........XOOOo .",
".........XOOoO .",
"....XXXXXXOOoo .",
"..XXOOOOOOOoOo .",
".XOOO     Oooo .",
".XOOO ...XoOoX .",
"XOOOO ...XOooo .",
"XOOOo ...XooXo .",
"XOOoO ...XoooX .",
"XOoOo ...XooXX .",
"XOooo ...XoXoX .",
"XoOoo ...XXoXX .",
"XOooo XXXXoXXX .",
"XoooooXoXoXXXX .",
"               ."
};
static unsigned char *al_font_e[] = {
"................",
"................",
"................",
"XXXXXXXXXX .....",
"XOOOOOOOOO .....",
"XOOOO      .....",
"XOOOO ..........",
"XOOOO XXXXX ....",
"XOOOOOOOoOo ....",
"XOOOO       ....",
"XOOoo ..........",
"XOoOo ..........",
". Ooo ..........",
". ooo XXXXXXXX .",
"..  ooXooXoXXX .",
"....           ."
};
static unsigned char *al_font_f[] = {
"....XXXXXX ..",
"..XXOOOOOO ..",
".XOOO      ..",
".XOOO .......",
"XOOOO XXXXX .",
"XOOOOOOOoOo .",
"XOOOo       .",
"XOOoo .......",
"XOoOX .......",
"XOooo .......",
"XoOoX .......",
"XooXo .......",
"XoXoX .......",
"XXoXX .......",
"XoXXX .......",
"      ......."
};
static unsigned char *al_font_g[] = {
"................",
"................",
"................",
"XXXXXXXXX ......",
"XOOOOOOOO ......",
"XOOOO     ......",
"XOOOO ..........",
"XOOOO .XXXXXXX .",
"XOOOO .XOOOoXo .",
"XOOOO .   oooo .",
"XOOOo ...XooXX .",
"XOOoO ...XoXoX .",
". oOo ...XXoXX .",
". Ooo XXXXoXXX .",
"..  ooXoXoXXXX .",
"....           ."
};
static unsigned char *al_font_h[] = {
"XXXXX ..........",
"XOOOO ..........",
"XOOOO ..........",
"XOOOO XXXXX.....",
"XOOOOOOoOoo  ...",
"XOOOO     ooo ..",
"XOOOo ...Xooo ..",
"XOOOo ...Xoooo .",
"XOOoO ...XooXo .",
"XOoOo ...XXooo .",
"XOooo ...XooXX .",
"XoOoo ...XoXoX .",
"XOooX ...XXoXX .",
"XoooX ...XoXXX .",
"XooXX ...XXXXX .",
"      ...      ."
};
static unsigned char *al_font_i[] = {
".XXXX .",
"XOOOo .",
"      .",
".......",
"XXXXX .",
"XOOOO .",
"XOOOo .",
"XOOoO .",
"XOOoo .",
"XOoOX .",
"XOooo .",
"XooXo .",
"XoXoX .",
"XooXX .",
"XoXXX .",
"      ."
};
static unsigned char *al_font_j[] = {
"..........XXXX .",
".........XOOoo .",
".........      .",
"................",
".....XXXXXXXXX .",
".....XOOOOOOoO .",
".....     OOoo .",
".........XOoOX .",
".........XOooo .",
".........XOoXX .",
".........XoXoX .",
".........XooXX .",
".........XXoX ..",
"XXXXXXXXXoooX ..",
"XoooooooXoX  ...",
"           ....."
};
static unsigned char *al_font_k[] = {
"XXXXX ..........",
"XOOOO ..........",
"XOOOO ..........",
"XOOOo ...XXXXX .",
"XOOOo ...Xooo ..",
"XOOoO ...Xooo ..",
"XOOoo XXXXoo ...",
"XOOoOoooooo ....",
"XOoOo     oo ...",
"XOooo ...Xooo ..",
"XoOoX ...XoXo ..",
"XOooo ...XooXo .",
"XooXX ...XoXXX .",
"XoXoX ...XXoXX .",
"XooXX ...XoXXX .",
"      ...      ."
};
static unsigned char *al_font_l[] = {
"XXXXX ..",
"XOOOO ..",
"XOOOo ..",
"XOOOo ..",
"XOOoO ..",
"XOOoo ..",
"XOoOo ..",
"XOooo ..",
"XoOoo ..",
"XOooX ..",
"Xoooo ..",
"XooXo ..",
"XoXoX ..",
"XXoXX X.",
"XoXXXX .",
"       ."
};
static unsigned char *al_font_m[] = {
".......................",
".......................",
".......................",
"XXXXXXXXXXXXXXXXXX.....",
"XOOOOOOOOOOOOOoOoo  ...",
"XOOOO    OOOO    ooo ..",
"XOOOO ..XOOoO ..Xooo ..",
"XOOOO ..XOOoo ..XooXo .",
"XOOOo ..XOoOo ..Xoooo .",
"XOOOo ..XoOoX ..XooXo .",
"XOOoX ..Xoooo ..XoXoX .",
"XOoOo ..XoXoX ..XooXX .",
"XOooX ..XooXX ..XoXXX .",
"XoOoX ..XoXXX ..XXoXX .",
"XooXX ..      ..XoXXX .",
"      ..........      ."
};
static unsigned char *al_font_n[] = {
"................",
"................",
"................",
"XXXXXXXXXXX.....",
"XOOOOOOOOoO  ...",
"XOOOO     ooo ..",
"XOOOo ...Xooo ..",
"XOOoO ...Xoooo .",
"XOOoo ...XoooX .",
"XOoOo ...XooXo .",
"XOooX ...XoooX .",
"XoOoo ...XoXoX .",
"XOoXo ...XooXX .",
"XoXoX ...XXoXX .",
"XooXX ...XoXXX .",
"      ...      ."
};
static unsigned char *al_font_o[] = {
"................",
"................",
"................",
"....XXXXXXXXXX .",
"..XXOOOOOOOOoO .",
".XOOO     OoOo .",
".XOOO ...XoOoo .",
"XOOOo ...XOooX .",
"XOOoO ...XooXo .",
"XOoOo ...XoooX .",
"XOooo ...XoXoX .",
"XoOoo ...XooXX .",
"XOooo ...XXoX ..",
"Xoooo XXXXoXX ..",
"XooooooXoXX  ...",
"           ....."
};
static unsigned char *al_font_p[] = {
"................",
"................",
"................",
"XXXXXXXXXX .....",
"XOOOOOOOOoO  ...",
"XOOOO     ooo ..",
"XOOOo ...XooX ..",
"XOOoO ...Xoooo .",
"XOOoo ...XoXoX .",
"XOoOo XXXXXoXX .",
"XOooooooXooXXX .",
"XooXo          .",
"XOooX ..........",
"XoXoX ..........",
"XooXX ..........",
"      .........."
};
static unsigned char *al_font_q[] = {
"................",
"................",
"................",
"....XXXXXXXXXX .",
"..XXOOOOOOOOoO .",
".XOOO     Oooo .",
".XOOO ...XoOXo .",
"XOOOo ...Xoooo .",
"XOOoO ...XoXoX .",
"XOOoo ...XXoXX .",
"XOoOo ...XoXXX .",
"XOooo ...      .",
"XoOoo ..........",
"XOooo XXXXXXXX .",
"XoooooXoXXXXXX .",
"               ."
};
static unsigned char *al_font_r[] = {
"..............",
"..............",
"..............",
"....XXXXXXXX .",
"..XXOOOOOoOo .",
".XOOO        .",
".XOOo ........",
"XOOoO ........",
"XOOoo ........",
"XOoOo ........",
"XOooX ........",
"XooXo ........",
"XOooX ........",
"XoXoX ........",
"XooXX ........",
"      ........"
};
static unsigned char *al_font_s[] = {
"................",
"................",
"................",
"....XXXXXX .....",
"..XXOOOOOO .....",
".XOOO      .....",
".XOOO ..........",
"XOOOO XXXXX.....",
"XOOOOOOoOoo  ...",
"          ooo ..",
".........XooX ..",
".........XoooX .",
"XXXXX ...XoXoX .",
"XOOOO XXXXooXX .",
"XOOooOooXoXXXX .",
"               ."
};
static unsigned char *al_font_t[] = {
"XXXXX ...",
"XOOOO ...",
"XOOOO ...",
"XOOOO XX.",
"XOOOOOO .",
"XOOOo   .",
"XOOoO ...",
"XOoOo ...",
"XOooo ...",
"XoOoX ...",
"XOooo ...",
"XooXo ...",
"XoXoX ...",
"XooXX XX.",
"XoXXXXX .",
".       ."
};
static unsigned char *al_font_u[] = {
"................",
"................",
"................",
"XXXXX ...XXXXX .",
"XOOOO ...XOOoo .",
"XOOOO ...XOoOo .",
"XOOOo ...XOooo .",
"XOOOo ...XoOoo .",
"XOOoO ...XoooX .",
"XOOoo ...XooXo .",
"XOoOo ...XoooX .",
"XOooo ...XoXoX .",
". OoO ...XooXX .",
". ooo XXXXXoXX .",
"..  oooooXoXXX .",
"....           ."
};
static unsigned char *al_font_v[] = {
"................",
"................",
"................",
"XXXXX ...XXXXX .",
"XOOOO ...XOOoO .",
"XOOOO ...XOoOo .",
"XOOOo ...XOooo .",
"XOOOo ...XoOoo .",
"XOOoO ...XoooX .",
"XOOoo ...Xoooo .",
"XOoOo ...XoXoX .",
"XOooo ...XooXX .",
"XoOoo ...XoXX ..",
"XOooo XXXXoXX ..",
"XooooooXoXX  ...",
"           ....."
};
static unsigned char *al_font_w[] = {
".......................",
".......................",
".......................",
"XXXXX ..........XXXXX .",
"XOOOO ..XXXXX ..XOOoO .",
"XOOOO ..XOOOo ..XOOoo .",
"XOOOO ..XOOoO ..XOoOo .",
"XOOOO ..XOOOo ..XOooX .",
"XOOOO ..XOOoO ..XoOoo .",
"XOOOO ..XOoOo ..XoooX .",
"XOOOo ..XOOoo ..XXoXX .",
"XOOOo ..XOooo ..XooXX .",
"XOOoo ..XoOoo ..XoXX ..",
"XOoOo XXXoooo XXXXXX ..",
"XoOooooooooXooXoXX  ...",
"                  ....."
};
static unsigned char *al_font_x[] = {
"................",
"................",
"................",
"XXXXX ...XXXXX .",
"XOOOO ...XOOoo .",
". OOO ...XOoO ..",
". OOO ...XOoo ..",
".. OO XXXXoO ...",
"... OOOoOoo ....",
"..XOo     oo ...",
".XOOo ...XXoo ..",
".XOoO ...XooX ..",
"XOoOo ...XoXXX .",
"XoooX ...XXoXX .",
"XooXX ...XoXXX .",
"      ...      ."
};
static unsigned char *al_font_y[] = {
"................",
"................",
"................",
"XXXXX ...XXXXX .",
"XOOOO ...XOOoo .",
"XOOOO ...XOoOo .",
"XOOOO ...XOOoo .",
". OOo ...Xooo ..",
". OOO ...XOoo ..",
".. Oo XXXXoo ...",
"... Ooooooo ....",
"....XoooXo .....",
"....XooXoX .....",
"....XoXoXX .....",
"....XXoXXX .....",
"....       ....."
};
static unsigned char *al_font_z[] = {
"................",
"................",
"................",
"...XXXXXXXXXXX .",
"...XOOOOOOOoOo .",
"...     OOoOoo .",
".......XOoOoo ..",
"......XOOooo ...",
".....XOOoOo ....",
"....XOOooo .....",
"...XOooOo ......",
"..XOoOoo .......",
".XOoOoo ........",
"XooooooXXXXXXX .",
"XooooXooXoXXXX .",
"               ."
};

static unsigned char **aluminium_font[] = {
	/* unprintables */
	al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc,
	al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc,
	/* space onward */
	al_font_spc, al_font_exc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_apos, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc,
	/* numerics */
	al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc,
	/* uppercase */
	al_font_spc, al_font_a, al_font_b, al_font_c, al_font_d, al_font_e, al_font_f, al_font_g, al_font_h, al_font_i, al_font_j, al_font_k, al_font_l, al_font_m, al_font_n, al_font_o,
	al_font_p, al_font_q, al_font_r, al_font_s, al_font_t, al_font_u, al_font_v, al_font_w, al_font_x, al_font_y, al_font_z, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc,
	/* lowercase */
	al_font_spc, al_font_a, al_font_b, al_font_c, al_font_d, al_font_e, al_font_f, al_font_g, al_font_h, al_font_i, al_font_j, al_font_k, al_font_l, al_font_m, al_font_n, al_font_o,
	al_font_p, al_font_q, al_font_r, al_font_s, al_font_t, al_font_u, al_font_v, al_font_w, al_font_x, al_font_y, al_font_z, al_font_spc, al_font_spc, al_font_spc, al_font_spc, al_font_spc
};
